### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by ChaerilM** [waleedahmad/Laravel-Facebook-SDK#1]
Hi, thanks for awesome tutorial, 
I just realize that you did not register `FacebookServiceProvider` to app in the tutorial, although in the repo it was registered, took me a while to realize it why my app_id not working.

The login function can only register user if they are logged out `due to $this->middleware('guest')->except('logout');` and had same email between fb and application, i'm planning to use this as 'Integrate to Facebook' which required users becoming user and integrate their facebook for automatic post to facebook. I was thinking about moving socialite to graphcontroller, but it had it's own middleware that requires a fb account logged in

**Comment by waleedahmad** [comment]
In Laravel 5.5 and greater, we don't have to register Service Providers. Laravel's Package Auto-Discovery takes care of it. If you're below 5.4, you have to manually register it in your `$providers` array in `config/app.php` file.

**Comment by ChaerilM** [comment]
i'm on 5.7, for facebook sdk yes it will be automatically found via autoload and package:discover. but GraphServiceProvider is not as we manually create it. 
![with provider](https://user-images.githubusercontent.com/1352081/45424979-473eaa80-b6c2-11e8-9b6d-be25860849a4.png)
![without provider](https://user-images.githubusercontent.com/1352081/45424980-473eaa80-b6c2-11e8-997c-fe504030642f.png)
what did i miss?

**Comment by waleedahmad** [comment]
Error message clearly says that you need to pass a valid `app_id` and `app_secret` when creating an instance of Facebook class. You need to define these three env variables in your `.env` file. 

`FACEBOOK_CLIENT_ID=YOUR_APP_ID`
`FACEBOOK_CLIENT_SECRET=YOUR_APP_SECRET`
`FACEBOOK_REDIRECT=https://localhost:3000/login/facebook/callback`

They are being used in [config/services.php](https://github.com/waleedahmad/Laravel-Facebook-SDK/blob/master/config/services.php#L38). When creating an instance of Facebook, we retrieve them from services.php in [FacebookServiceProvider.php](https://github.com/waleedahmad/Laravel-Facebook-SDK/blob/master/app/Providers/FacebookServiceProvider.php#L28) with Laravel's `config` helper method and construct Facebook object with it which Laravel then injects into IoC container.

**Comment by ChaerilM** [comment]
Yes, I've read the tutorial, if it was config there should be same error on both image. since the only difference on both was adding providers and not adding it.

**Comment by waleedahmad** [comment]
With these images, it's not possible debug the issue you're facing. Reach out on [Facebook](https://www.facebook.com/devxdesign/) page and i'll try to help you.
